---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dwwfoeqh/public_html/
    - /bin/cp -R $DEPLOYPATH $DEPLOYPATH.backup-$(date +%s)
    - npm install
    - npm run build
    - /bin/cp -R build/* $DEPLOYPATH
    - echo "Deployed at $(date)" > $DEPLOYPATH/deployment-status.txt
