/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HypertensionRouteImport } from './routes/hypertension'
import { Route as FineHealthRouteImport } from './routes/fine-health'
import { Route as DiabetesRouteImport } from './routes/diabetes'
import { Route as IndexRouteImport } from './routes/index'

const HypertensionRoute = HypertensionRouteImport.update({
  id: '/hypertension',
  path: '/hypertension',
  getParentRoute: () => rootRouteImport,
} as any)
const FineHealthRoute = FineHealthRouteImport.update({
  id: '/fine-health',
  path: '/fine-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DiabetesRoute = DiabetesRouteImport.update({
  id: '/diabetes',
  path: '/diabetes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diabetes': typeof DiabetesRoute
  '/fine-health': typeof FineHealthRoute
  '/hypertension': typeof HypertensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diabetes': typeof DiabetesRoute
  '/fine-health': typeof FineHealthRoute
  '/hypertension': typeof HypertensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diabetes': typeof DiabetesRoute
  '/fine-health': typeof FineHealthRoute
  '/hypertension': typeof HypertensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diabetes' | '/fine-health' | '/hypertension'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diabetes' | '/fine-health' | '/hypertension'
  id: '__root__' | '/' | '/diabetes' | '/fine-health' | '/hypertension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiabetesRoute: typeof DiabetesRoute
  FineHealthRoute: typeof FineHealthRoute
  HypertensionRoute: typeof HypertensionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hypertension': {
      id: '/hypertension'
      path: '/hypertension'
      fullPath: '/hypertension'
      preLoaderRoute: typeof HypertensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-health': {
      id: '/fine-health'
      path: '/fine-health'
      fullPath: '/fine-health'
      preLoaderRoute: typeof FineHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diabetes': {
      id: '/diabetes'
      path: '/diabetes'
      fullPath: '/diabetes'
      preLoaderRoute: typeof DiabetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiabetesRoute: DiabetesRoute,
  FineHealthRoute: FineHealthRoute,
  HypertensionRoute: HypertensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
